services:
    nginx:
        image: "nginx:alpine"
        ports:
            -   "8000:80"
        volumes:
            -   ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            -   ./learnphp:/var/www/html
    php:
        build:
            context: dockerfiles
            dockerfile: php.dockerfile
        volumes:
            -   ./learnphp:/var/www/html
    postgresql:
        image: postgres:16-alpine
        ports:
            -   "5432:5432"
        env_file:
            -   env/postgres.env
    composer:
        build:
            context: dockerfiles
            dockerfile: composer.dockerfile
        volumes:
            -   ./learnphp:/var/www/html